name: Gitee repos mirror periodic job
on:
  push:
  schedule:
    - cron: '0 9 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/gitee-mirror-action@v0.01
      with:
        src: github/cubxxw
        dst: gitee/xxw3293172751
        dst_key: ${{ secrets.GITEE_TOKEN }}
        dst_token: ${{ secrets.GITEE_PRIVATE_KEY }}
    - name: Commit changes
      env:
        GIT_SSH_COMMAND: "ssh -i ${{ secrets.GITEE_TOKEN }}"
        GIT_AUTHOR_NAME: "Your name"
        GIT_AUTHOR_EMAIL: "Your email"
      run: |
        git remote add origin https://gitee.com/xxw3293172751/cubxxw.git
        git config user.name "${{ env.GIT_AUTHOR_NAME }}"
        git config user.email "${{ env.GIT_AUTHOR_EMAIL }}"
        git add .
        git commit -a -s  --allow-empty -m "Periodic commit"
        git push -u origin master
